name: Build EuxOS ISO

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Fix script line endings
        run: |
          sudo apt update
          sudo apt install -y dos2unix
          dos2unix build-euxos.sh

      - name: Make script executable
        run: chmod +x build-euxos.sh

      - name: Build ISO
        run: sudo ./build-euxos.sh

      - name: Check ISO exists
        run: ls -lh EuxOS.iso

      - name: Upload EuxOS ISO
        uses: actions/upload-artifact@v4
        with:
          name: EuxOS-ISO
          path: EuxOS.iso
